dist: trusty
sudo: required

language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir builddir-Debug   && cd builddir-Debug   && cmake -DCMAKE_BUILD_TYPE=Debug ..   && make -j $(nproc) && cd ..
  - mkdir builddir-Release && cd builddir-Release && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j $(nproc) && cd ..
